name: Go

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install deps
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install deps
      run: go mod download

    - name: Test
      run: go test -v ./